Alumno1 = float(input("Ingrese la Calificacion del alumno 1"))
Alumno2 = float(input("Ingrese la Calificacion del alumno 2"))
Alumno3 = float(input("Ingrese la Calificacion del alumno 3"))
Alumno4 = float(input("Ingrese la Calificacion del alumno 4"))
Alumno5 = float(input("Ingrese la Calificacion del alumno 5"))