Alumno1 = float(input("Ingrese la Calificacion del alumno 1"))
Alumno1 = float(input("Ingrese la Calificacion del alumno 1"))
Alumno1 = float(input("Ingrese la Calificacion del alumno 1"))
Alumno1 = float(input("Ingrese la Calificacion del alumno 1"))
Alumno1 = float(input("Ingrese la Calificacion del alumno 1"))